### ISSUE TITLE
Question dns redirect

### ISSUE THREAD

**Issue by atze09** [xgcssch/SystaComfortPrometheusExporter#1]
Hello,
How can i do this.
I tried hours to get it working via  raspberry which is in bridging mode, but i was not successful.
My Setup is Fritzbox 7490 and Zyxel GS1900 as network switch.
Maybe you can help me.
Thanks a lot. 
Best Regards,
Dominik

**Comment by xgcssch** [comment]
Hello Dominik!
What is the root problem: 
Is the DNS resolution for `paradigma.remoteportal.de` not working or do you have trouble starting the container/program?
Best regards
Sönke

P. S.
If you're from germany you may switch to german if you like. ;-)

**Comment by atze09** [comment]
Hallo Sönke,
Mein Problem ist noch, dass der Lan Controller meines RPi 4 keine DHCP vom WLAN Adapter bzw. der Fritzbox dahinter bekommt.
Das Problem ist leider hier nicht richtig aufgehoben. Deine Packages laufen trocken schon ohne Fehler.
Meine Frage zielte eher darauf ab, mit welcher Hardware ich dies sonst auch bewerkstelligen könnte.
nach meinen Recherchen kann mein Zyxel GS1900 zwar VLAN aber kein dns redirect, oder sehe ich das falsch.
Mit welcher Hardware hast du das gelöst bzw. hast du noch einen Vorschlag wie sich das ab schlankesten lösen lässt?

Denk schon einmal.
Freundliche Grüße,
Dominik

**Comment by xgcssch** [comment]
Wenn du dem Raspi eine feste IP zuordnest, könntest du dort lokal einen DNS Server betreiben (https://www.deviceplus.com/raspberry-pi/how-to-use-a-raspberry-pi-as-a-dns-server/):
dort konfigurierst du dann die Fritzbox als Upstream DNS Server und zusätzlich den Eintrag 
`address=/paradigma.remoteportal.de/192.168.0.6` 
für das Portal.
In der Paradigma Konfiguration musst du dann die Adresse des Pi als DNS Server eintragen.

Meine Konfiguration hilft dir nicht viel, da diese ungleich komplexer ist.
Gruß
Sönke

**Comment by atze09** [comment]
Danke das schaue ich mir an. Alternativ bin ich gerade noch auf die Idee gekommen eine openwrt Bridge welche ich noch herumliegen habe zu benutzen.
Danke schonmal für deine Hilfe. Ich mache das hier zu da das Problem ja nicht mit deinem Tool zusammen hängt.
