### ISSUE TITLE
systacomfort_inside2_temperature_celsius

### ISSUE THREAD

**Issue by tobiasfiechter** [xgcssch/SystaComfortPrometheusExporter#12]
Der Wert systacomfort_inside2_temperature_celsius liefert bei mir konstant 18°. 18° ist aber die "Raumtemperatur Soll". systacomfort_inside_temperature_celsius scheint korrekt zu funktionieren.

**Comment by xgcssch** [comment]
Hast du zufällig mal analysiert, welcher Wert denn die Raumtemperatur wirklich ist. Ich habe keine Raumtemperatursensoren in meiner Anlage, daher kann ich das selber nicht sehen.

**Comment by tobiasfiechter** [comment]
Hallo, sorry für die späte Antwort und danke für dein Feedback
Die aktuelle Raumtemperatur finde ich leider nicht unter /metrics, sie ist aber ersichtlich im App (S-Touch).
Der Wert systacomfort_inside2_temperature_celsius scheint momentan statisch bei 20.5° zu sein (wie der Sollwert in der App).

**Comment by tobiasfiechter** [comment]
Will be fixed with https://github.com/xgcssch/SystaComfortPrometheusExporter/pull/20
