### ISSUE TITLE
Rück und Vorlauf

### ISSUE THREAD

**Issue by tobiasfiechter** [xgcssch/SystaComfortPrometheusExporter#13]
Ist hier der solar Rück und Vorlauf gemeint? Bei meinen Messungen ist hier der Wert systacomfort_solarpanel_return_temperature_celsius jeweils am Tag tiefer als systacomfort_solarpanel_supply_temperature_celsius. So ist meine Annahme, dass systacomfort_solarpanel_return_temperature_celsius eigentlich der Solarpanelvorlauf ist und systacomfort_solarpanel_supply_temperature_celsius ist der Solarpanelrücklauf?

https://github.com/xgcssch/SystaComfortPrometheusExporter/blob/c12634400886f50ae95c666d37ece65a60bfc678/internal/pkg/udpserver/prometheuscounter.go#L251

**Comment by xgcssch** [comment]
Entschuldige bitte die späte Antwort!
Ich stimme dir zu: die Werte sind vertauscht!
