### ISSUE TITLE
SystaComfort sendet keine Werte an das Remoteportal

### ISSUE THREAD

**Issue by LeoDJ** [xgcssch/SystaComfortPrometheusExporter#17]
#### Versionen:
> Software: V2.14 7.07.20
> Hardware: V2.10
> Basis-System: V0.37.13
> SystaComfort II (In Firmware Tab von SystaService): V2.14.2

## Problem
Ich hatte alles so eingerichtet wie in der Readme erklärt und die SystaComfort mit dem SystaService Tool so eingestellt wie beschrieben.  
Nur blieben leider alle Werte des Prometheus Exporters auf 0.

Beim genaueren Nachforschen habe ich folgendes herausgefunden:
- UDP Pakete erreichen den Docker Container ohne Probleme
- Die SystaComfort schickt nur einfach keine Pakete, obwohl sie exakt so konfiguriert ist wie in dem Screenshot
- Wenn ich den "Remote-Portal Reset" Button im Servicetool drücke, erreicht den Docker Container alle 6 Sekunden ein 40 Byte großes UDP Paket auf dem richtigen Port, aber mehr nicht
  - Der Docker Container antwortet auch nicht auf die Anfrage
  - Im Paket stehen ein paar unzuordenbare Bytes und der ASCII Text "`RESET PASSWORD!!`"
- Da es sich hierbei vermutlich um eine Initialisierung mit der Cloud handelt habe ich den DNS Eintrag nochmal auf die originale Cloud zurückgebogen
- Diese schickt auch tatsächlich eine Antwort auf die Anfrage und danach hört die SystaComfort auf diese 40 Byte Pakete zu senden, sendet aber auch keine anderen. 
  - (Habe tcpdump etwa 15min weiter laufen lassen, auf dem Port kam kein einziges weiteres Paket mehr)
- Im Bedienpanel unter System > Kontrolle steht der Status SystaWeb auf "Datenüb.gesperrt"

## Hypothese
- Ich habe keinen freigeschalteten Remoteportal Zugang
- Eventuell bedeutet die Antwort des Portals "der User ist nicht freigeschaltet, du musst keine Daten senden, auch wenn du so konfiguriert bist"

Ich bin mir nicht sicher, ob ich etwas falsch gemacht habe. Ich wäre tatsächlich davon ausgegangen, dass die Daten kontinuierlich gesendet werden, egal ob für das RemotePortal Feature bezahlt wird oder nicht.

Hattest du ein ähnliches Problem schonmal und weißt eventuell was ich da tun könnte?

## Dump der Pakete zum/vom RemotePortal, nach Drücken des "Remote-Portal Reset" Buttons

![grafik](https://user-images.githubusercontent.com/5898657/191493864-e6594a1a-2029-44a2-9305-334f27fc73f4.png)
![grafik](https://user-images.githubusercontent.com/5898657/191493874-4f9a5f48-c577-4850-8add-e66652358638.png)

**Comment by S-Bil** [comment]
Hallo LeoDJ
Ruf bitte bei Paradigma Support 0715753591301 an. Da wird Dir gerne weiter geholfen. 
Grüße 
Serge

**Comment by LeoDJ** [comment]
Okay, ich glaube ich habe das Problem bereits gefunden. Anscheinend muss man die Datenübertragung lokal am Bedienpanel freigeben.

Die Option "Web-Portal SystaWeb" sehe ich allerdings nicht über die S-Touch Oberfläche. Ich nehme an, dass man diese Option ähnlich wie die "Gebäudeleitsystem" Einstellung nicht per Remotezugang ändern kann, was ja durchaus sinnvoll ist.  

Leider bin ich erst wieder in ein paar Tagen vor Ort, um die Theorie zu testen. Ich werde das Issue auf dem Laufenden halten, sobald ich mehr weiß.

![grafik](https://user-images.githubusercontent.com/5898657/191509685-736f825b-95a4-4b2f-8b3a-7cc911296059.png)
![grafik](https://user-images.githubusercontent.com/5898657/191511006-fb7da7b5-ab60-482d-af87-ff6c08cb0a0c.png)
(Screenshots aus dem [Installationshandbuch SystaComfort HW v2.0](https://mam-downloadcenter.paradigma.de/page/download?assetid=47529&assetname=TH-2610_V2.0_0420_SystaComfort_II_Touch_II_Install.pdf))

**Comment by LeoDJ** [comment]
Jap, genau das war das Problem. Musste lokal am Bedienpanel das Web-Portal erlauben. 

Darauf bin ich natürlich aus der Ferne nicht drauf gekommen, weil der Menüeintrag per S-Touch komplett fehlt.

(Es sind doch immer die trivialsten Sachen ^^')
