### ISSUE TITLE
curl metrics access showing "0" and system parameters

### ISSUE THREAD

**Issue by atze09** [xgcssch/SystaComfortPrometheusExporter#3]
Hallo ich bins schon wieder und nun auf der Zielgerade:-)
Es läuft nun soweit alles nur kommen bei den Werten sehr viele Programm und Systemparameter zurück, diese werden ja auch gespeichert und nehmen nur Speicherplatz weg oder?
Gibt es eine Möglichkeit diese zu deaktivieren?
Das zweite Problem ist, dass bei den Heizungswerten überall "0" steht, das hängt wahrscheinlich noch mit der Verschlüsselung zusammen. Leider habe ich von meinem Heizungsbauer noch keine Rückinfo wann ich das Programm bekommen kann.
ich habe gedacht ich probier es mal ob es vielleicht ab Werk gar nicht aktiviert ist.

`pi@raspberrypi:~ $ curl http://192.168.17.192:2112/metrics
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 0.000361869
go_gc_duration_seconds{quantile="0.25"} 0.00041682
go_gc_duration_seconds{quantile="0.5"} 0.000494696
go_gc_duration_seconds{quantile="0.75"} 0.000533065
go_gc_duration_seconds{quantile="1"} 0.004615259
go_gc_duration_seconds_sum 0.010923317
go_gc_duration_seconds_count 14
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 11
# HELP go_info Information about the Go environment.
# TYPE go_info gauge
go_info{version="go1.15.3"} 1
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 363264
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 1.2889272e+07
# HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
# TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 723692
# HELP go_memstats_frees_total Total number of frees.
# TYPE go_memstats_frees_total counter
go_memstats_frees_total 6275
# HELP go_memstats_gc_cpu_fraction The fraction of this program's available CPU time used by the GC since the program started.
# TYPE go_memstats_gc_cpu_fraction gauge
go_memstats_gc_cpu_fraction 1.5461236593582138e-05
# HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
# TYPE go_memstats_gc_sys_bytes gauge
go_memstats_gc_sys_bytes 1.27088e+06
# HELP go_memstats_heap_alloc_bytes Number of heap bytes allocated and still in use.
# TYPE go_memstats_heap_alloc_bytes gauge
go_memstats_heap_alloc_bytes 363264
# HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
# TYPE go_memstats_heap_idle_bytes gauge
go_memstats_heap_idle_bytes 6.914048e+06
# HELP go_memstats_heap_inuse_bytes Number of heap bytes that are in use.
# TYPE go_memstats_heap_inuse_bytes gauge
go_memstats_heap_inuse_bytes 983040
# HELP go_memstats_heap_objects Number of allocated objects.
# TYPE go_memstats_heap_objects gauge
go_memstats_heap_objects 1449
# HELP go_memstats_heap_released_bytes Number of heap bytes released to OS.
# TYPE go_memstats_heap_released_bytes gauge
go_memstats_heap_released_bytes 6.18496e+06
# HELP go_memstats_heap_sys_bytes Number of heap bytes obtained from system.
# TYPE go_memstats_heap_sys_bytes gauge
go_memstats_heap_sys_bytes 7.897088e+06
# HELP go_memstats_last_gc_time_seconds Number of seconds since 1970 of last garbage collection.
# TYPE go_memstats_last_gc_time_seconds gauge
go_memstats_last_gc_time_seconds 1.6097648357685237e+09
# HELP go_memstats_lookups_total Total number of pointer lookups.
# TYPE go_memstats_lookups_total counter
go_memstats_lookups_total 0
# HELP go_memstats_mallocs_total Total number of mallocs.
# TYPE go_memstats_mallocs_total counter
go_memstats_mallocs_total 7724
# HELP go_memstats_mcache_inuse_bytes Number of bytes in use by mcache structures.
# TYPE go_memstats_mcache_inuse_bytes gauge
go_memstats_mcache_inuse_bytes 3472
# HELP go_memstats_mcache_sys_bytes Number of bytes used for mcache structures obtained from system.
# TYPE go_memstats_mcache_sys_bytes gauge
go_memstats_mcache_sys_bytes 16384
# HELP go_memstats_mspan_inuse_bytes Number of bytes in use by mspan structures.
# TYPE go_memstats_mspan_inuse_bytes gauge
go_memstats_mspan_inuse_bytes 30720
# HELP go_memstats_mspan_sys_bytes Number of bytes used for mspan structures obtained from system.
# TYPE go_memstats_mspan_sys_bytes gauge
go_memstats_mspan_sys_bytes 32768
# HELP go_memstats_next_gc_bytes Number of heap bytes when next garbage collection will take place.
# TYPE go_memstats_next_gc_bytes gauge
go_memstats_next_gc_bytes 4.194304e+06
# HELP go_memstats_other_sys_bytes Number of bytes used for other system allocations.
# TYPE go_memstats_other_sys_bytes gauge
go_memstats_other_sys_bytes 920752
# HELP go_memstats_stack_inuse_bytes Number of bytes in use by the stack allocator.
# TYPE go_memstats_stack_inuse_bytes gauge
go_memstats_stack_inuse_bytes 491520
# HELP go_memstats_stack_sys_bytes Number of bytes obtained from system for stack allocator.
# TYPE go_memstats_stack_sys_bytes gauge
go_memstats_stack_sys_bytes 491520
# HELP go_memstats_sys_bytes Number of bytes obtained from system.
# TYPE go_memstats_sys_bytes gauge
go_memstats_sys_bytes 1.1353084e+07
# HELP go_threads Number of OS threads created.
# TYPE go_threads gauge
go_threads 10
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 1
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1.048576e+06
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 10
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 8.31488e+06
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.60976270883e+09
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 8.2315264e+08
# HELP process_virtual_memory_max_bytes Maximum amount of virtual memory available in bytes.
# TYPE process_virtual_memory_max_bytes gauge
process_virtual_memory_max_bytes -1
# HELP promhttp_metric_handler_requests_in_flight Current number of scrapes being served.
# TYPE promhttp_metric_handler_requests_in_flight gauge
promhttp_metric_handler_requests_in_flight 1
# HELP promhttp_metric_handler_requests_total Total number of scrapes by HTTP status code.
# TYPE promhttp_metric_handler_requests_total counter
promhttp_metric_handler_requests_total{code="200"} 2
promhttp_metric_handler_requests_total{code="500"} 0
promhttp_metric_handler_requests_total{code="503"} 0
# HELP systacomfort_boiler_active_info Is the boiler is running
# TYPE systacomfort_boiler_active_info gauge
systacomfort_boiler_active_info 0
# HELP systacomfort_boiler_circulationpump_info Is the boiler circulation pump running
# TYPE systacomfort_boiler_circulationpump_info gauge
systacomfort_boiler_circulationpump_info 0
# HELP systacomfort_boiler_error_info Errorinformation of the boiler
# TYPE systacomfort_boiler_error_info gauge
systacomfort_boiler_error_info 0
# HELP systacomfort_boiler_heatercircuitpump_info Is the heatercircuit pump running
# TYPE systacomfort_boiler_heatercircuitpump_info gauge
systacomfort_boiler_heatercircuitpump_info 0
# HELP systacomfort_boiler_loadpump_info Is the boiler loading running
# TYPE systacomfort_boiler_loadpump_info gauge
systacomfort_boiler_loadpump_info 0
# HELP systacomfort_boiler_return_temperature_celsius The boiler return temperature
# TYPE systacomfort_boiler_return_temperature_celsius gauge
systacomfort_boiler_return_temperature_celsius 0
# HELP systacomfort_boiler_runtime_seconds The total runtime of the boiler
# TYPE systacomfort_boiler_runtime_seconds gauge
systacomfort_boiler_runtime_seconds 0
# HELP systacomfort_boiler_starts_total The number of boiler starts
# TYPE systacomfort_boiler_starts_total gauge
systacomfort_boiler_starts_total 0
# HELP systacomfort_boiler_status_info State of the boiler
# TYPE systacomfort_boiler_status_info gauge
systacomfort_boiler_status_info 0
# HELP systacomfort_boiler_supply_temperature_celsius The boiler supply temperature
# TYPE systacomfort_boiler_supply_temperature_celsius gauge
systacomfort_boiler_supply_temperature_celsius 0
# HELP systacomfort_boiler_supply_upperlimit_celsius The upper limit of the supply temperature
# TYPE systacomfort_boiler_supply_upperlimit_celsius gauge
systacomfort_boiler_supply_upperlimit_celsius 0
# HELP systacomfort_boiler_target_temperature_celsius The boiler target temperature
# TYPE systacomfort_boiler_target_temperature_celsius gauge
systacomfort_boiler_target_temperature_celsius 0
# HELP systacomfort_boiler_torch_info Is the torch of the boiler active
# TYPE systacomfort_boiler_torch_info gauge
systacomfort_boiler_torch_info 0
# HELP systacomfort_heatcurve_gradient_celsius The gradient of the heating curve
# TYPE systacomfort_heatcurve_gradient_celsius gauge
systacomfort_heatcurve_gradient_celsius 0
# HELP systacomfort_heatcurve_rootpoint_celsius The rootpoint of the heating curve
# TYPE systacomfort_heatcurve_rootpoint_celsius gauge
systacomfort_heatcurve_rootpoint_celsius 0
# HELP systacomfort_heatercircuit_return_temperature_celsius The boiler return temperature
# TYPE systacomfort_heatercircuit_return_temperature_celsius gauge
systacomfort_heatercircuit_return_temperature_celsius 0
# HELP systacomfort_heatercircuit_supply_temperature_celsius The boiler supply temperature
# TYPE systacomfort_heatercircuit_supply_temperature_celsius gauge
systacomfort_heatercircuit_supply_temperature_celsius 0
# HELP systacomfort_inside_target_temperature_celsius The inside target temperature
# TYPE systacomfort_inside_target_temperature_celsius gauge
systacomfort_inside_target_temperature_celsius 0
# HELP systacomfort_inside_temperature_celsius The inside temperature
# TYPE systacomfort_inside_temperature_celsius gauge
systacomfort_inside_temperature_celsius 0
# HELP systacomfort_mode_info The current mode
# TYPE systacomfort_mode_info gauge
systacomfort_mode_info 0
# HELP systacomfort_outside_temperature_celsius The outside temperature
# TYPE systacomfort_outside_temperature_celsius gauge
systacomfort_outside_temperature_celsius 0
# HELP systacomfort_solarpanel_maximum_temperature_celsius Maximum temperature of the liquid in the solar panal today
# TYPE systacomfort_solarpanel_maximum_temperature_celsius gauge
systacomfort_solarpanel_maximum_temperature_celsius 0
# HELP systacomfort_solarpanel_outside_temperature_celsius The outside temperature measured on the solar heating panel
# TYPE systacomfort_solarpanel_outside_temperature_celsius gauge
systacomfort_solarpanel_outside_temperature_celsius 0
# HELP systacomfort_solarpanel_return_temperature_celsius The temperature of the liquid streaming from the solar heating panel
# TYPE systacomfort_solarpanel_return_temperature_celsius gauge
systacomfort_solarpanel_return_temperature_celsius 0
# HELP systacomfort_solarpanel_supply_temperature_celsius The temperature of the liquid streaming into the solar heating panel
# TYPE systacomfort_solarpanel_supply_temperature_celsius gauge
systacomfort_solarpanel_supply_temperature_celsius 0
# HELP systacomfort_solarpanel_temperature_celsius The temperature of the liquid in solar heating panel
# TYPE systacomfort_solarpanel_temperature_celsius gauge
systacomfort_solarpanel_temperature_celsius 0
# HELP systacomfort_tapwater_target_temperature_celsius The tapwater target temperature
# TYPE systacomfort_tapwater_target_temperature_celsius gauge
systacomfort_tapwater_target_temperature_celsius 0
# HELP systacomfort_tapwater_temperature_celsius The tapwater temperature
# TYPE systacomfort_tapwater_temperature_celsius gauge
systacomfort_tapwater_temperature_celsius 0
# HELP systacomfort_watercirculation_temperature_celsius The temperature in the water circulation
# TYPE systacomfort_watercirculation_temperature_celsius gauge
systacomfort_watercirculation_temperature_celsius 0
`

**Comment by xgcssch** [comment]
Kontaktiere mich doch mal unter melchizedek.vaiden@usweek.net (eine Woche lang gültig). Ev. kann ich ja mit dem Programm aushelfen.
Außerdem habe ich eine neue Version erstellt, welche die Metriken für GO und dem Prozess nicht exportiert.

**Comment by atze09** [comment]
> Kontaktiere mich doch mal unter [melchizedek.vaiden@usweek.net](mailto:melchizedek.vaiden@usweek.net) (eine Woche lang gültig). Ev. kann ich ja mit dem Programm aushelfen.
> Außerdem habe ich eine neue Version erstellt, welche die Metriken für GO und dem Prozess nicht exportiert.

Perfekt hab ich getan und danke für das Update muss ich beim Docker noch ein Argument hinzufügen wenn ich die process metrics nicht möchte?
