### ISSUE TITLE
Serviceprogramm Paradigma

### ISSUE THREAD

**Issue by tobiasfiechter** [xgcssch/SystaComfortPrometheusExporter#6]
Hi,

Is it possible to download the Serviceprogramm Paradigma somewhere? I cannot find the software online and don't have it either.

Thank you

**Comment by xgcssch** [comment]
Hallo Tobias!
Ich habe heute eine FAQ Sektion hinzugefügt:
https://github.com/xgcssch/SystaComfortPrometheusExporter/blob/main/README_de.md#faq
Da habe ich auch diese Frage beantwortet.
Aber melde dich trotzdem mal unter johnathan.johnanthony@usweek.net bei mir.
Sönke

**Comment by tobiasfiechter** [comment]
Hallo

Du hast mir letzte Woche eine Mail wegen dem "*Serviceprogramm Paradigma".* Ich
habe mal Paradigma angeschrieben aber leider bisher keine Rückmeldung
erhalten. Könntest auch du mir die Software zukommen lassen?

Liebe Grüsse
Tobias

Am Sa., 23. Jan. 2021 um 21:39 Uhr schrieb Sönke Schau <
notifications@github.com>:

**Comment by matze1007** [comment]
Leider kann man das Programm nicht bei Paradigma runter laden. Nur für Fachhandwerker. 
Wie schalte ich jetzt diese Datenübertragung frei? Da kauft man ne Heizung für teuer Geld und kann sie nicht mal ins Smart Home hängen

**Comment by xgcssch** [comment]
> 

Hallo @matze1007 !
Letztlich musst du aber ja einen Heizungsbauer als Ansprechpartner haben. Kann der dir nicht weiterhelfen?
Ich kann nur sagen: meiner ist da super hilfsbereit und hat mir das alles problemlos zur Verfügung gestellt.
Sönke

**Comment by S-Bil** [comment]
Hallo @matze1007 !
Um die Datenübertragung frei zu schalten brauchst Du keine SystaService Programm.
Datenübertragung für SystaWeb. am Touch Display: System > Einstellungen > Datenübertragung SystaWeb (Gesperrt / Erlaubt)
nur am Hauptbedienteil einstellbar (Bedienteil-ID15)

Die Modbus Schnittstelle muss man auch am Bedienteil (ID 15) freischalten. 
System > Einstellungen > ModBus TCP-Server <-> lesen und schreiben

**Comment by matze1007** [comment]
> Hallo @matze1007 ! Um die Datenübertragung frei zu schalten brauchst Du keine SystaService Programm. Datenübertragung für SystaWeb. am Touch Display: System > Einstellungen > Datenübertragung SystaWeb (Gesperrt / Erlaubt) nur am Hauptbedienteil einstellbar (Bedienteil-ID15)
> 
> Die Modbus Schnittstelle muss man auch am Bedienteil (ID 15) freischalten. System > Einstellungen > ModBus TCP-Server <-> lesen und schreiben

Leider habe ich kein Touch Bedienteil. War leider nicht verfügbar. Und mit dem Tastenbedienteil habe ich die Menüpunkte leider nicht.
Was habe ich sonst noch für Möglichkeiten ?
Bedienteil am Kessel ist ein Touch und der Modbus Server.

**Comment by S-Bil** [comment]
https://github.com/xgcssch/SystaComfortPrometheusExporter/issues/6#issuecomment-988726121
Kontrollprogramm > Status abfragen > SystaWeb > Erlaubt einstellen [Einsteller wird nur am Servicebedienteil angezeigt]
Falls es mit +/- Tasten nicht verstellbar ist, dann:
Brücke Service am Bedienteil anklemmen (mittlere Klemme),
Bedienteil an Bus Control Boiler an Comfort II Platine anschließen

**Comment by matze1007** [comment]
> [#6 (comment)](https://github.com/xgcssch/SystaComfortPrometheusExporter/issues/6#issuecomment-988726121) Kontrollprogramm > Status abfragen > SystaWeb > Erlaubt einstellen [Einsteller wird nur am Servicebedienteil angezeigt] Falls es mit +/- Tasten nicht verstellbar ist, dann: Brücke Service am Bedienteil anklemmen (mittlere Klemme), Bedienteil an Bus Control Boiler an Comfort II Platine anschließen

Bei mir ist leider

Kontrollprogramm > Status abfragen > SystaWeb > gesperrt :-( kann auch mit  + und - nix einstellen.
Mein Tastenbedienteil ist außen auf die SystaComfort2 geschraubt und das Kabel steckt auf Bus Control 1.
Links daneben ist der Bus Control Boiler.
Muss ich das Bedienteil dann von der Systa runter schrauben um die Brücke machen zu können ?
Und dann umstecken auf Bus Control Boiler ?
Habe ich dann mehr Rechte oder was ändert sich da ?

Ich hoffe, da kann nichts passieren. Nicht das danach gar nix mehr läuft.

**Comment by S-Bil** [comment]
@matze1007 
Es wird nichts passieren, aber zuerst bitte den Regler stromlos machen.
Das Bedienteil einfach von unten nach oben aufklappen, dann in die zwei mittlere Klemmen eine Drahtbrücke machen. Somit wird das Bedienteil von dem 1. Heizkreis zum Service-Bedienteil gemacht. Danach auf der Platine umstecken.
Strom an und die Einstellungen werden freigegebene.

**Comment by matze1007** [comment]
> @matze1007 Es wird nichts passieren, aber zuerst bitte den Regler stromlos machen. Das Bedienteil einfach von unten nach oben aufklappen, dann in die zwei mittlere Klemmen eine Drahtbrücke machen. Somit wird das Bedienteil von dem 1. Heizkreis zum Service-Bedienteil gemacht. Danach auf der Platine umstecken. Strom an und die Einstellungen werden freigegebene.

Also die mittlere Klemm in der unteren Reihe bez. B1 ?

Oder die mittlere klemme oben bez. OT ?

Jetzt habe ich gelesen Bus 1 und Bus 2 wären nur für das Touch Display. Das tastendisplay muss immer an Bus Boiler. Macht das einen Unterschied, wo das Bedienteil steckt ?
Mal abgesehen von Service Modus

**Comment by S-Bil** [comment]
NEIN NICHT AN B1 ODER OT!

**Comment by S-Bil** [comment]
die mittleren Klemmen am Bedienteil teil
**Das Bedienteil einfach von unten nach oben aufklappen, dann in die zwei mittlere Klemmen eine Drahtbrücke machen.**
Am Bedienteil mit tasten hinten.... ist eine Klemmbrett mit 6 Klemmen, die mittleren 2 überbrücken, also Klemme 3 und 4 von rechte oder von linke Seite gesehen

**Comment by matze1007** [comment]
>
OK. Dann will ich das versuchen.
Mein Tastenfeld ist direkt auf die Systa geschraubt.

**Comment by matze1007** [comment]
@S-Bil 
Habe das Bedienteil geöfnet. Klemmen sind sogar mit Service Beschriftet. Die anderen mit BUS und Heizkreis2.
Morgen werde ich das ganze mal testen. Heute leider keine Zeit mehr.
Nochmal zum Anschluß Bedienteil: Für den Service Modus muss ich es mit der Brücke im Display auf BUS BOILER stecken.
Nachdem ich die Einstellung gemacht habe, Spannung aus > Brücke raus > wieder umstecken auf BUS 1 (oder kann/muss das Tastenbedienteil auf BUS BOILER stecken bleiben ?) > Spannung wieder an

**Comment by S-Bil** [comment]
@matze1007 
Man kann alles so lassen, Brücke und Bus Control Boiler.

**Comment by matze1007** [comment]
@S-Bil 
danke für die tolle Anleitung. Habe es heute gemacht. Hat alles funktioniert. 
Jetzt kann ich mich an Setup hier wagen...

Hab das mit dem DNS Umleiten schon mal getestet. Funktioniert aber irgendwie nur auf dem PI wo der DNS Server läuft.
Wenn ich da ein lookup mache, zeigt das Portal auf die IP wo das Script laufen soll. Mache ich den lookop auf einem anderen Rechner, sehe ich die IP von Paradigma.
Habe auf der Fritzbox den Lokalen DNS Server (Raspberry PI) eingetragen .... funktioniert irgendwie nicht.
Muss ich noch weiter testen.

**Comment by marvinGitHub** [comment]
@tobiasfiechter I can upload the SystaService 1.58 software, please let me know where i can upload this.

**Comment by zanandreisfilippo** [comment]
hello, on my s-touch panel I can't find the part to enable the modbus configuration. anyone can help me? I have software version V2.14 and hardware version V2.10. on the systa main board i have no jumpers and on the back of the touch display i have only the BUS terminals. Thank you very much

**Comment by alexej86** [comment]
> @tobiasfiechter I can upload the SystaService 1.58 software, please let me know where i can upload this.

Hi, have you already uploaded the SystaService somewhere? I would be happy about the link :)

**Comment by marvinGitHub** [comment]
@alexej86 please have a look at my repo which contains serveral firmware files and the service app https://github.com/marvinGitHub/systa-bridge/tree/master/assets

**Comment by alexej86** [comment]
> @alexej86 please have a look at my repo which contains serveral firmware files and the service app https://github.com/marvinGitHub/systa-bridge/tree/master/assets

Thank you very much for your link! 

What is the user level experience pin which is asked by the SystaService when it is started? I used some random numbers and found out that the gui is different depending on the pin

**Comment by marvinGitHub** [comment]
There are only two different PINS 1212 and 2121 you need to check the differences.
