### ISSUE TITLE
Exporter liefert keine Daten obwohl UDP Pakete der Heizung empfangen werden

### ISSUE THREAD

**Issue by xgcssch** [xgcssch/SystaComfortPrometheusExporter#7]
Unterdessen gibt es mehrere Anwender, welche den Exporter zum Laufen gebracht, die Heizung zum Senden von Daten überredet haben welche auch beim Exporter ankommen, der Exporter jedoch nur Nullwerte exportiert.
Die Arbeitshypothese ist, dass unterschiedliche Software- oder Hardwarestände der SystaControl Abweichungen im Protokoll aufweisen.
In diesem Issue erfasse ich die Informationen zu dem Problem.
HenningS81 hat mir netterweise zwei Mitschnitte der Kommunikation zur Analyse überlassen.

**Comment by xgcssch** [comment]
Also ich habe heute den Trace von Henning und einen von meinem System anlaysiert - beide zu finden im Git Branch `SystaComfortUnresponsive` unter `assets\Traces`:

Generell ist der Ablauf folgendermaßen:
Die Steuerung schickt permanent ein UDP Paket an die Zieladresse `paradigma.remoteportal.de`. Gibt es noch keine aktive Kommunikation, dann hat das Paket hat einen Pakettyp (Feld in den Daten) von `0`. Empfängt der Exporter ein Paket, so schaut er sich den Pakettyp an. Pakettypen ungleich `0` sind Datenpakete und enthalten die Nutzdaten der Heizung. Dort werden auch die zu exportierenden Daten extrahiert.

In jedem Fall wird aber ein Antwortpaket an die Steuerung geschickt, welche Daten beinhaltet die auf den empfangenen Daten basieren. Konkret werden ein Teil der MAC Adresse und ein übermittelter Counter verwendet.
Dieses Antwortpaket veranlasst die Steuerung, weiter Daten zu senden.

Der Fall bei dem dieses funktioniert ist in der Aufzeichnung `Working.pcapng` festgehalten, der Fall wo es nicht klappt in `NotWorking.pcapng`.

Bei der Generierung des Antwortpaketes wird sowohl auf den MAC Adressteil, als auch auf den Counter eine "magische" Konstante addiert. Ich habe diesen Code aus dem ursprünglichen Perl Programm übernommen und heute Tests gemacht, ob dieses Verfahren notwendig ist: leider ja. Meine Steuerung liefert auch keine Daten zurück, wenn ich dort was ändere.
Da ich 

Sollte dieses die Ursache sein, dann ist das Problem, dass wir entweder ein funktionierende Kommunikation mitschneiden, oder schlicht probieren müssen welche Konstanten funktionieren. Ohne Anhaltspunkte könnten diese alles sein: Geburtsdatum der Programmierin, ... 

Ausprobieren ist dabei schwierig, da die Pakete nur alle 6 Sekunden kommen. Ev. hat ja noch jemand eine "echte" Verbindung zu dem SystaWeb Portal und kann die Kommunikation mitschneiden (Bitte unverschlüsselt!).

Bei Paradigma hatte ich bereits Anfang 2018 nachgefragt, ob sie mir eine Beschreibung des Protokolls schicken könnten. Leider Fehlanzeige, nur ein Verweis auf die Modbus/TCP Implementierung, welche bei mir zumindest nicht aktiv ist.

Insofern bin ich jetzt mit meinem Latein am Ende.

Eventuell habt ihr ja noch Ideen.

Hier nochmal eine kurze Analyse der Kommunikation:
```
Läuft - bspw. bei meiner Anlage:

Von SystacomfortII
0000   f8 ca b8 3b b9 6a>2c be 97 00 66 16<08 00 45 00  => MAC lt. EthernetII Header: 2c:be:97:00:66:16
0010   04 34 3a cf 00 00 40 11 f1 5e c0 a8 64 fa c0 a8
0020   64 40 1f 42 57 bc 04 20 62 2d>00 97 be 2c 16 66< => MAC lt. Datenheader 00 97 be 2c 16 66 -> 6 Byte in der Reihenfolge 33 22 11 00 55 44
0030  >88 e8<09 09 0c 00 33 df 00 00 00 00 00 00 00 18  => Counter 88 e8 = e888
0040   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 02
...

An SystacomfortII
0000   2c be 97 00 66 16 f8 ca b8 3b b9 6a 08 00 45 00
0010   00 30 43 c9 00 00 80 11 00 00 c0 a8 64 40 c0 a8
0020   64 fa 57 bc 1f 42 00 1c 4a b9>00 97 be 2c 16 66< => MAC des Zielsystems (aus den Daten)
0030   88 e8 00 00 00 00 01 00 00 00 99 f4 47 28        => Counter; 00 00 00 00; 01; 00 00 00; (66(Offset 5) << 8) + 16(Offset 4) + 8e83(Magie1) = f4 99; Counter + 3FBF(Magie2) = (1)2847

Läuft nicht - bspw. bei Hennings Anlage:

Sender MAC lt. Header: 40:d1:c6:ef:fe:db

Von SystacomfortII
0000   00 11 32 cf e1 a7>40 d1 c6 ef fe db<08 00 45 00  => MAC lt. EthernetII Header: 40 d1 c6 ef fe db
0010   04 34 39 6b 00 00 40 11 57 bd c0 a8 b2 3b c0 a8
0020   b2 04 1f 42 57 bc 04 20 e0 be>ef c6 d1 40 db fe< => MAC lt. Datenheader ef c6 d1 40 db fe -> 6 Byte in der Reihenfolge 33 22 11 00 55 44
0030  >47 cc<09 09 0c 00 33 df 00 00 00 00 00 00 00 18  => Counter 47 cc = cc47
0040   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 02
0050   48 9c 0b 42 09 00 03 24 00 00 13 03 87 03 00 00

An SystacomfortII
0000   40 d1 c6 ef fe db 00 11 32 cf e1 a7 08 00 45 00
0010   00 30 ef 92 40 00 40 11 65 99 c0 a8 b2 04 c0 a8
0020   b2 3b 57 bc 1f 42 00 1c 58 ba>ef c6 d1 40 db fe< => MAC des Zielsystems (aus den Daten)
0030   47 cc 00 00 00 00 01 00 00 00 5e 8d 06 0c        => Counter; 00 00 00 00; 01; 00 00 00; (fe(Offset 5) << 8) + db(Offset 4) + 8e83 = (1)8d5e; Counter + 3FBF = (1)0C06
```

**Comment by HenningS81** [comment]
Hi Sönke,

danke für Deine ganzen Forschungen. Basiert die Kommunikation mit den anderen Tools vielleicht auf einem ähnlichen Mechanismus und kann man da die Kommunikation mitschneiden?

Viele Grüße

**Comment by atze09** [comment]
`Läuft nicht - bspw. bei Dominiks Anlage:

Sender MAC lt. Header: 2C:BE:97:00:97:64

Von SystacomfortII
0000   00 00 00 01 00 06-2c be 97 00 97 64-00 06 08 00  => MAC lt. EthernetII Header: 2C:BE:97:00:97:64
0010   45 00 04 34 62 2a 00 00 40 11 70 83 c0 a8 11 b9
0020   c0 a8 11 02 1f 42 57 bc 04 20 c5 38 00 97 be 2c< => MAC lt. Datenheader c5 38 00 97 be 2c
0030  -64 97-fb 32 09 09 0c 00 33 df 00 00 00 00 00 00  => Counter 47 cc = cc47
0040   00 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0050   00 02 08 9c 0a 42 40 00 80 a4 00 00 5b 1b 07 02

An SystacomfortII (Mehrere Antworten)
0000   00 04 00 01 00 06 b8 27 eb 37 78 2a 24 0b 08 00
0010   45 00 00 30 cc 4f 40 00 40 11 ca 61 c0 a8 11 02
0020   c0 a8 11 b9 57 bc 1f 42 00 1c a4 39 00 97 be 2c
0030   64 97 fc 32 00 00 00 00 01 00 00 00 e7 25 bb 72

0000   00 04 00 01 00 06 b8 27 eb 37 78 2a 00 00 08 00
0010   45 00 00 30 94 2c 40 00 40 11 02 85 c0 a8 11 02
0020   c0 a8 11 b9 57 bc 1f 42 00 1c a4 39 00 97 be 2c
0030   64 97 3f 39 00 00 00 00 01 00 00 00 e7 25 fe 78

0000   00 04 00 01 00 06 b8 27 eb 37 78 2a 2e 39 08 00
0010   45 00 00 30 95 64 40 00 40 11 01 4d c0 a8 11 02
0020   c0 a8 11 b9 57 bc 1f 42 00 1c a4 39 00 97 be 2c
0030   64 97 40 39 00 00 00 00 01 00 00 00 e7 25 ff 78

Irgendwie scheint meine Antowort komplett anders auszusehen.
Woher bekomme ich die "Mac lt.Datenheader"?
Ich kann gerne noch weitere Informationen zur Verfügung stellen.

**Comment by HenningS81** [comment]
Hallo Sönke,

ich habe jetzt mal auf die 1.26 aktualisiert. Das macht leider keinen Unterschied. Soll ich dann trotzdem auch nochmal ein Log erzeugen?

Viele Grüße,

Henning

**Comment by atze09** [comment]
> Hallo Sönke,
> 
> ich habe jetzt mal auf die 1.26 aktualisiert. Das macht leider keinen Unterschied. Soll ich dann trotzdem auch nochmal ein Log erzeugen?
> 
> Viele Grüße,
> 
> Henning

Hallo Henning,
1.26 in Firmware in der Heizung?

Grüße,
Dominik

**Comment by HenningS81** [comment]
Hallo Dominik,

ja genau. Ich habe die Hardware Version 1, da scheint das die letzte verfügbare Version zu sein.

Gruß,

Henning

**Comment by atze09** [comment]
> Hallo Dominik,
> 
> ja genau. Ich habe die Hardware Version 1, da scheint das die letzte verfügbare Version zu sein.
> 
> Gruß,
> 
> Henning

Hallo Henning,

Dann werde ich mich wohl um eine gebrauchte Steuerung Rev. 1 bemühen müssen.
Freundliche Grüße,
Dominik

**Comment by xgcssch** [comment]
Hallo Henning!
Ich habe im Readme einen Hinweis eingefügt, dass mit Hardware 2 eine Steuerung der Anlage über Modbus TCP möglich ist.
Ev. solltest du diese Möglichkeit nutzen.
Ich mach das hier mal zu, da wir wahrscheinlich keine weiteren Erkenntnisse erhalten.
Gruß
Sönke
